[project]
name = "autostorage-opi-demo"
version = "0.1.0"
description = "autostorage v0.0.15 + OPI demo."
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "automol==0.0.24",
    "autostorage==0.0.16",
    # "automol",
    # "autostorage",
    "irmsd>=0.1.1",
    "orca-pi==2.0.0",
]

[tool.ty.environment]
python = ".venv/bin/python"
root = ["autostorage_opi_demo"]

[tool.ty.rules]
unsupported-operator = "ignore"

[tool.ruff]
src = ["autostorage_opi_demo"]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "N999",         # Invalid module name
    "CPY001",       # Copyright at top of file
    "COM812",       # Trailing comma
    "T201",         # Print statement
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.uv.sources]
# autostorage = { path = "../autostorage", editable = true }
# automol = { path = "../automol", editable = true }
